// Embedded kernel symbol table for backtraces and panic output. The table is
// generated by tools/gensyms.py from the first link pass and linked into the
// .ksymtab section (see kernel/lib/symbols.S and the Makefile).
#pragma once

#include <lib/types.h>

// Parses the embedded table. Safe to call before anything else; lookups
// return nullptr if the table is absent or empty.
void symbols_init();
usize symbols_count();

// Returns the name of the symbol containing addr and sets *offset to the
// distance from its start, or nullptr if addr precedes every symbol.
const char* symbols_lookup(u64 addr, u64* offset);
